name: Docker Image CI
on:
  push:
    branches: [ master ]
    tags: '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up tag name
      run: |
        echo "tag_name=$(echo ${{ github.ref }} | sed -e 's#refs/tags/##g' | sed -e 's#refs/heads/##g')" >> $GITHUB_ENV
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:${{ env.tag_name }}
